### ISSUE TITLE
Figure out how to set the can node

### ISSUE THREAD

**Issue by nielstron** [nielstron/pyblnet#41]
The reason I was hesitant about merging this change is other reports like [this one](https://community.home-assistant.io/t/hooking-up-the-uvr1611-via-blnet/37846/142) where users report that setting the node works fine for them - maybe the current endpoint is missing something (i.e. maybe there can be different nodes connected, enumerable by alphabetical notation?) 

@whatashit Could it be that you have different CAN nodes connected? Or do you find any relationship between some number on the device and the blaA / blaB access to nodes?

**Comment by whatashit** [comment]
Well what I figured out so far. 
First of all I had the feeling everything works just fine using a simple config with just the resource and scan_interval as I am only having one can node besides the blnet.
This worked but after some hours stopped. I took a look at the web frontend of the blnet and saw that the radio button for detected node 1 is not set. I set it manually and everything worked again. After some hours same issue.
So I tried to use the 'can_node' option. Which made me end up in hell with totally misconfigured blnet.
I first thought the blnet is broken and bought another one from second hand. Same behaviour.
After analyzing the code and verifying with web inspection I found out that blA is used instead of blB. BTW in June 2021 user "mahomh" reported same behaviour and solved it with a cronjob. See here: https://community.home-assistant.io/t/hooking-up-the-uvr1611-via-blnet/37846/96

**Comment by whatashit** [comment]
I have an idea why it seems to work for some people. If u dont use the can_node option and set it manually in the web frontend it will work if the UVR is continuously transmitting additinal data to blnet. This can be configured in web fronted under CAN-Network > analoge / digitale Eingänge (which is different to real in/outputs). 
I tried this option and I had the feeling it works 24h+ but my UVR 1611 (first model) got so damn slow it didnt even do anything anymore. So this was not an option for me.
Anyways I will setup asap and see if it works

**Comment by whatashit** [comment]
Well I still got the issue on how to tell HA to use the new version of pyblnet.
I thought changing the __init__.py of blnet in custom components would make HA download nad use the correct version.

`REQUIREMENTS = [
    'pyblnet==0.9.1'
]`

I changed this to:

`REQUIREMENTS = [
    'pyblnet==0.9.2'
]`

But no matter how often I restart or even reboot HA I seem to always end up with version 0.9.1.
Unfortunately I am running HA on a micro computer with non-removable, soldered storage memory. Therefore I have no access to the downloaded python packages.... Or is there a way to access those?

**Comment by nielstron** [comment]
Regarding the version, I think you need to update the [`manifest.json`](https://github.com/nielstron/ha_blnet/blob/master/custom_components/blnet/manifest.json) requirements since newer HA versions

**Comment by whatashit** [comment]
Yes. Just found this out while browsing through the files. Now it seems to be working.
Now its setup. Running after startup of HA. Webfrontend looks good. Radiobutton is correctly set by HA. BLD node number is not getting modified.
I would say so far its perfect.
I will see within the next 2 days whats happening.

**Comment by whatashit** [comment]
@nielstron : Short update: After almost 24h it still works. No connection lost. Nothing I have to set manually. Compared to old pyblnet version the new one works like a charm.

**Comment by whatashit** [comment]
Still running perfect. I would say test finished.

**Comment by nielstron** [comment]
Thanks for testing! I guess next up is bumping the version in the custom component.
