### ISSUE TITLE
[Documentation] Difference between  BLNETWeb, BLNET, BLNETDirect

### ISSUE THREAD

**Issue by henfri** [nielstron/pyblnet#9]
Hello,

could you please document the difference between these three variants to access the Data?

Regards,
Hendrik

**Comment by nielstron** [comment]
Are you satisfied with the current state of the documentation?

If not please state questions left open.

**Comment by nielstron** [comment]
I see. As this is quite a small package and not used that heavily, I'll try to keep the overhead as small as possible and thus keep the documentation in the code. I commented the example code in the README more so that the intended usage of the method becomes clearer.

Yes all changes are primarily applied to the dev branch. The master branch stores the current (most stable) state of the pypi package.

**Comment by henfri** [comment]
Hello,

I understand a bit better now.
In the BLNet class, if both methods are active, the analog and digital values are collected twice.

Don't you think that it would be better to omit the analog and digital values read from the web-interface if Direct is active?

Greetings,
Hendrik

**Comment by nielstron** [comment]
No, every interface can be turned on and off separately to give the user as much control as possible.
